#!/bin/sh

user=`whoami`
path="/Users/$user/Library/Application Support/Sublime Text 3"
snippets="$path/Packages/User/ff-snippets"
heroku="$path/Packages/Theme - Heroku"
solarized="$path/Packages/Theme - Solarized"
spacegray="$path/Packages/Theme - Spacegray"
pwdheroku="sublime/color-schemes/Packages/Theme - Heroku"
pwdsolarized="sublime/color-schemes/Packages/Theme - Solarized"
pwdspacegray="sublime/color-schemes/Packages/Theme - Spacegray"

echo "Setting up Bash..."
ln -s `pwd`/bash         ~/.bash
ln -s `pwd`/bashrc       ~/.bashrc
ln -s `pwd`/bash_profile ~/.bash_profile
ln -s `pwd`/profile      ~/.profile
ln -s `pwd`/gemrc        ~/.gemrc

echo "Installing Sublime configs..."
cp -r ./*sublime* ./color-schemes "$path/Packages/User"

echo "Installing snippets..."
if [[ ! -d $snippets ]]; then
  cd "$path/Packages/User" && git clone git@github.com:filipesf/ff-snippets.git
else
  cd "$snippets" && git pull
fi

echo "Creating 'subl' symlink..."
sudo ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

echo "Installing Solarized..."
if [[ ! -d $solarized  ]]; then
  cp -r $pwdsolarized $solarized
fi

echo "Installing Spacegray..."
if [[ ! -d $spacegray  ]]; then
  cp -r $pwdspacegray $spacegray
fi

echo "Installing Heroku..."
if [[ ! -d $heroku  ]]; then
  cp -r $pwdheroku $heroku
fi
