#!/bin/sh

# REMOVE ORIGINAL FILES
rm -rf ~/.bashrc ~/.bash_profile ~/.zshrc ~/.oh-my-zsh ~/.aliases ~/.utils ~/.gitconfig ~/.gitignore ~/.gitcommit ~/.vim ~/.vimrc ~/.gemrc ~/.ackrc ~/.editorconfig

# BASH
echo "Creating Bash symlinks..."
ln -s `pwd`/bashrc ~/.bashrc
ln -s `pwd`/aliases ~/.aliases
ln -s `pwd`/bash_profile ~/.bash_profile

# ZSH
echo "Creating ZSH symlinks..."
ln -s `pwd`/zshrc ~/.zshrc
ln -s `pwd`/oh-my-zsh ~/.oh-my-zsh

# GIT
echo "Creating GIT symlinks..."
ln -s `pwd`/gitconfig ~/.gitconfig
ln -s `pwd`/gitignore ~/.gitignore
ln -s `pwd`/gitcommit ~/.gitcommit

# VIM
echo "Creating VIM symlinks..."
ln -s `pwd`/vim ~/.vim
ln -s `pwd`/vimrc ~/.vimrc

# RUBY GEMS
echo "Creating Gems symlink..."
ln -s `pwd`/gemrc ~/.gemrc

# EditorConfig
echo "Creating EditorConfig symlink..."
ln -s `pwd`/editorconfig ~/.editorconfig
