#!/bin/sh

# BASH
echo "Creating Bash symlinks..."
ln -s `pwd`/bashrc ~/.bashrc
ln -s `pwd`/bash_profile ~/.bash_profile

# GIT
echo "Creating GIT symlinks..."
ln -s `pwd`/gitconfig ~/.gitconfig
ln -s `pwd`/gitignore ~/.gitignore
ln -s `pwd`/gitcommit ~/.gitcommit

# VIM
echo "Creating VIM symlinks..."
ln -s `pwd`/vim ~/.vim
ln -s `pwd`/vimrc ~/.vimrc

# Ack
echo "Creating Ack symlink..."
ln -s `pwd`/ackrc ~/.ackrc

# EditorConfig
echo "Creating EditorConfig symlink..."
ln -s `pwd`/editorconfig ~/.editorconfig
