#!/bin/sh

echo "Installing Homebrew..."
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing Oh My ZSH..."
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Installing You Tube Downloader..."
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

echo "Creating symlinks..."
rm -rf ~/.zshrc
ln -s `pwd`/shell/zshrc ~/.zshrc
ln -s `pwd`/shell/config ~/.config
ln -s `pwd`/shell/aliases ~/.aliases

echo "Setting up Git..."
ln -s `pwd`/git/gitconfig ~/.gitconfig
ln -s `pwd`/git/gitignore ~/.gitignore

echo "Setting up Vim..."
ln -s `pwd`/vim ~/.vim
ln -s `pwd`/vim/vimrc ~/.vimrc
vim +PluginInstall +qall

echo "Setting up Sublime..."
ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
cp -av `pwd`/sublime/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
cp -av `pwd`/sublime/Package\ Control.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.sublime-settings
cp -av `pwd`/sublime/Default\ \(OSX\).sublime-keymap ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Default\ (OSX).sublime-keymap
