#!/bin/sh

echo "Setting up Bash..."
if [[ ! -d ~/.bash ]]; then
  mkdir ~/.bash
fi

ln -s `pwd`/bash/git-aware-prompt ~/.bash/git-aware-prompt
ln -s `pwd`/bash/bash_profile ~/.bash_profile
ln -s `pwd`/bash/profile ~/.profile
ln -s `pwd`/bash/aliases ~/.aliases
ln -s `pwd`/bash/bashrc ~/.bashrc
ln -s `pwd`/ruby/gemrc ~/.gemrc

echo "Loading Sublime config files..."
user=`whoami`
path="/Users/$user/Library/Application Support/Sublime Text 3"
packages="$path/Packages"
snippets="$packages/User/ff-snippets"

echo "Setting up Sublime Text..."
cp -r ./*sublime* ./color-schemes "$path/Packages/User"

echo "Installing snippets..."
if [[ ! -d $snippets ]]; then
  cd "$packages/User" && git clone git@github.com:filipesf/ff-snippets.git
else
  cd "$snippets" && git pull
fi

echo "Creating 'subl' symlink..."
sudo ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

echo "Installing Sublime Themes"
if [[ ! -d $packages  ]]; then
  cp -r sublime/color-schemes/Packages/* $packages
fi

echo "Setting up Vim..."
ln -s `pwd`/vim ~/.vim
ln -s `pwd`/vim/colors ~/.vim/colors
ln -s `pwd`/vim/vimrc ~/.vimrc
vim +BundleInstall +qall

echo "Setting up Git..."

echo "Adding ignore to root"
cat ./git/ignore > ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global

echo "Adding attributes to root"
cat ./git/attributes > ~/.gitattributes

echo "User settings"
git config --global user.name "Filipe Fernandes"
git config --global user.email contato@filipefernandes.com.br
git config --global core.editor "subl -n -w"
git config --global color.ui true
git config --global push.default matching

echo "Setting up git-deff"

if [[ ! -d ~/bin ]]; then
  mkdir ~/bin
fi

cp ./git/git-diff.sh ~/bin/git-diff.sh
sudo chmod u+x ~/bin/git-diff.sh
git config --global diff.external ~/bin/git-diff.sh
